extern const GeoLayout castle_grounds_area_1_geo[];
extern const GeoLayout castle_grounds_area_1[];
extern const Collision castle_grounds_area_1_collision[];
extern const MacroObject castle_grounds_area_1_macro_objs[];
extern Lights1 castle_grounds_dl_grass_lights;
extern Lights1 castle_grounds_dl_under_lights;
extern Lights1 castle_grounds_dl_tower_lights;
extern u8 castle_grounds_dl_slop_ci8[];
extern u8 castle_grounds_dl_slop_pal_rgba16[];
extern u8 castle_grounds_dl_metal_ci8[];
extern u8 castle_grounds_dl_metal_pal_rgba16[];
extern u8 castle_grounds_dl_brick64_rgba16[];
extern Vtx castle_grounds_dl_Main_mesh_layer_1_vtx_0[29];
extern Gfx castle_grounds_dl_Main_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_Main_mesh_layer_1_vtx_1[32];
extern Gfx castle_grounds_dl_Main_mesh_layer_1_tri_1[];
extern Vtx castle_grounds_dl_Main_mesh_layer_1_vtx_2[20];
extern Gfx castle_grounds_dl_Main_mesh_layer_1_tri_2[];
extern Gfx mat_castle_grounds_dl_grass[];
extern Gfx mat_revert_castle_grounds_dl_grass[];
extern Gfx mat_castle_grounds_dl_under[];
extern Gfx mat_revert_castle_grounds_dl_under[];
extern Gfx mat_castle_grounds_dl_tower[];
extern Gfx castle_grounds_dl_Main_mesh_layer_1[];
