extern const GeoLayout castle_grounds_area_1_geo[];
extern const GeoLayout castle_grounds_area_1[];
extern const Collision castle_grounds_area_1_collision[];
extern const MacroObject castle_grounds_area_1_macro_objs[];
extern Lights1 castle_grounds_dl_Fast3D_Material_lights;
extern Lights1 castle_grounds_dl_sm64_water_mat_lights;
extern u8 castle_grounds_dl_shadow_ci4[];
extern u8 castle_grounds_dl_shadow_pal_rgba16[];
extern Vtx castle_grounds_dl_main_mesh_layer_1_vtx_0[22527];
extern Gfx castle_grounds_dl_main_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_Water_Box_Mesh_mesh_layer_1_vtx_0[4];
extern Gfx castle_grounds_dl_Water_Box_Mesh_mesh_layer_1_tri_0[];
extern Gfx mat_castle_grounds_dl_Fast3D_Material[];
extern Gfx mat_castle_grounds_dl_sm64_water_mat[];
extern Gfx mat_revert_castle_grounds_dl_sm64_water_mat[];
extern Gfx castle_grounds_dl_main_mesh_layer_1[];
extern Gfx castle_grounds_dl_Water_Box_Mesh_mesh_layer_1[];
